In [ ]:
import torch

In [ ]:
a=torch.tensor([5.], requires_grad=True)
b=torch.tensor([6.], requires_grad=True)

In [ ]:
y=a**3-b**2
y

tensor([89.], grad_fn=<SubBackward0>)

In [ ]:
#gradient of y


# dy/da = 3*a**2=3*25=75
# dy/db = -2b=2*6=-12



In [ ]:
y.backward() #Calculates gradients automatically

In [ ]:
#derivatives

a.grad

tensor([75.])

In [ ]:
b.grad

tensor([-12.])

In [ ]:
#example with y=wx+b

w=torch.rand(10,1, requires_grad=True)
b=torch.rand(1, requires_grad=True)
w

tensor([[0.8816],
        [0.3203],
        [0.6632],
        [0.2135],
        [0.5756],
        [0.4399],
        [0.1493],
        [0.1941],
        [0.3926],
        [0.3302]], requires_grad=True)

In [ ]:
x=torch.rand(1,10)

In [ ]:
res=torch.mm(x,w) + b

In [ ]:
loss=1-res #loss fn

In [ ]:
res.backward()

In [ ]:
w.grad

tensor([[0.1720],
        [0.7228],
        [0.4280],
        [0.3960],
        [0.0285],
        [0.9634],
        [0.7631],
        [0.4721],
        [0.9021],
        [0.8498]])

In [ ]:
b.grad

tensor([1.])

In [ ]:
loss


tensor([[-1.9915]], grad_fn=<RsubBackward1>)

In [ ]:
#updating weights:
lr=0.001

with torch.no_grad():
  w=w-lr*w.grad.data
w

tensor([[0.8814],
        [0.3195],
        [0.6628],
        [0.2131],
        [0.5756],
        [0.4389],
        [0.1485],
        [0.1936],
        [0.3917],
        [0.3294]])

In [ ]:
z=torch.rand(1,224,224)
z.shape

torch.Size([3, 224, 224])