In [ ]:
import torch
import numpy as np

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Tue Jul  5 13:08:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
data=[[1,2,3],[4,5,6]]

In [ ]:
type(data)

list

In [ ]:
np.array(data)
np.asarray(data)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data=torch.tensor(data)

In [ ]:
type(data)

torch.Tensor

In [ ]:
data.dtype

torch.int64

In [ ]:
nparr=np.random.rand(3,4)
nparr

array([[0.40794313, 0.6874751 , 0.85536515, 0.56097173],
       [0.80909699, 0.46581813, 0.39051894, 0.83894846],
       [0.43545362, 0.31725775, 0.83056009, 0.42020788]])

In [ ]:
torch.tensor(nparr)

tensor([[0.1469, 0.5086],
        [0.1834, 0.3880]], dtype=torch.float64)

In [ ]:
#0 dimensional single value tensor

scalar=torch.tensor(10)
scalar

tensor(10)

In [ ]:
#checking out dimensions with ndim

scalar.ndim

0

In [ ]:
#get the number from a tensor

scalar.item()

10

In [ ]:
#vector single dimension with many numbers

vector=torch.tensor([2,6,9,2,1,9])
vector

tensor([2, 6, 9, 2, 1, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([6])

In [ ]:
#matrix- 2 dimensional flexible vectors

matrix=torch.tensor([[3,7,9,1],[3,0,1,3,],[1,45,12,9,]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([3, 4])

In [ ]:
#tensor 3d dimensional

tensor=torch.tensor([[
                      [1,2,3],
                      [4,5,6],
                      [7,8,9],
                      [10,11,12]
                      ],
                     [
                      [324,658,124],
                      [345,5687,1234],
                      [135,345,246],
                      [2356,135,1345]
                     ]])

In [ ]:
tensor.shape

torch.Size([2, 4, 3])

In [ ]:
#random tensors

rando=torch.rand((4,4))

rando

tensor([[0.5744, 0.2902, 0.0446, 0.6655],
        [0.5768, 0.7312, 0.4493, 0.4539],
        [0.0550, 0.5527, 0.9222, 0.4016],
        [0.7119, 0.2560, 0.6637, 0.0619]])

In [ ]:
rando.dtype

torch.float32

In [ ]:
rando1=torch.rand((224,224,3))
rando1

tensor([[[0.4173, 0.9663, 0.7844],
         [0.6931, 0.6156, 0.6129],
         [0.3478, 0.2526, 0.6929],
         ...,
         [0.9452, 0.7556, 0.2357],
         [0.4960, 0.3041, 0.9059],
         [0.0962, 0.5312, 0.3834]],

        [[0.3603, 0.0052, 0.7263],
         [0.5620, 0.1598, 0.1878],
         [0.2754, 0.7582, 0.6865],
         ...,
         [0.2520, 0.0360, 0.8071],
         [0.7294, 0.3193, 0.9350],
         [0.2882, 0.2623, 0.0984]],

        [[0.3668, 0.8897, 0.4396],
         [0.5650, 0.8890, 0.0055],
         [0.4548, 0.2218, 0.9963],
         ...,
         [0.3265, 0.8413, 0.0726],
         [0.2392, 0.6151, 0.8669],
         [0.9950, 0.7855, 0.0686]],

        ...,

        [[0.1789, 0.1016, 0.4293],
         [0.3138, 0.9795, 0.7916],
         [0.3597, 0.2532, 0.4118],
         ...,
         [0.9854, 0.5090, 0.1683],
         [0.3923, 0.7594, 0.7018],
         [0.5442, 0.9216, 0.8600]],

        [[0.1748, 0.5807, 0.5952],
         [0.5913, 0.9358, 0.7290],
         [0.

In [ ]:
#zeros

torch.zeros((4,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#ones
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#copying shape

torch.zeros_like(rando1) #(224,224,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
rando1.device

device(type='cpu')

In [ ]:
tensor=torch.tensor([1,2,5,5])

In [ ]:
tensor=tensor +100
tensor

tensor([101, 102, 105, 105])

In [ ]:
torch.mul(tensor,100)

tensor([10100, 10200, 10500, 10500])

In [ ]:
tensor1=torch.tensor([1,2,3])

tensor1*tensor1

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)

tensor(42655)

In [ ]:
tensor @ tensor

tensor(42655)

In [ ]:
import torch

In [ ]:
%%time

val=0
for i in range(len(tensor)):
  val+=tensor[i]*tensor[i]

val  


CPU times: user 1.48 ms, sys: 112 µs, total: 1.59 ms
Wall time: 1.41 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 627 µs, sys: 150 µs, total: 777 µs
Wall time: 535 µs


tensor(55)

In [ ]:
tensorA=torch.tensor([
                      [1,2],
                      [4,5],
                      [7,8]
                      ])

tensorB=torch.tensor([
                      [11,22],
                      [44,55],
                      [77,88]
                      ])

In [ ]:
print(tensorB.T)

tensor([[11, 44, 77],
        [22, 55, 88]])


In [ ]:
torch.matmul(tensorA,tensorB.T)

tensor([[  55,  154,  253],
        [ 154,  451,  748],
        [ 253,  748, 1243]])

In [ ]:
tensorA.shape
tensorB.T.shape

torch.Size([2, 3])

In [ ]:
#shortform for matmul---mm

torch.mm(tensorA,tensorB.T)

tensor([[  55,  154,  253],
        [ 154,  451,  748],
        [ 253,  748, 1243]])

In [ ]:
x=torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
x.sum()

tensor(450)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.type(torch.int16)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int16)

In [ ]:
x.reshape(1,10)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
x.view(1,10)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
xstack=torch.stack([x,x,x,x,x], dim=0)

In [ ]:
xstack.shape

torch.Size([5, 10])

In [ ]:
import torch

In [ ]:
x=torch.arange(0,10,1)

In [ ]:
x.shape

torch.Size([10])

In [ ]:
x=x.reshape(1,10)
x.shape

torch.Size([1, 10])

In [ ]:
x.squeeze()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.unsqueeze(0)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [16]:
y=torch.rand(224,224,3)

In [19]:
#permute

y=y.permute(2,0,1)
y.shape

torch.Size([3, 224, 224])

In [30]:
#indexing

y=torch.arange(1,10).reshape(1,3,3)

y


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [32]:
#goes from outer dim to inner dim

print(y[0])
print(y[0][0])
print(y[0][0][0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [36]:
#using : for all the dimensions and ,-- for the next dimension

y[:, :,0]

tensor([[1, 4, 7]])

In [37]:
y[:,1,1]

tensor([5])

In [38]:
y[0,0,:]

tensor([1, 2, 3])

In [42]:
import numpy as np

y=torch.arange(1,10)
ynp=y.numpy()

ynp.dtype

dtype('int64')

In [44]:
y=torch.from_numpy(ynp)
y.dtype

torch.int64

In [46]:
x=torch.rand(3,3)
x

tensor([[0.4105, 0.3982, 0.0130],
        [0.9071, 0.7670, 0.6648],
        [0.0242, 0.5658, 0.7484]])

In [48]:
##seeding--flavours of randomness

seed_number=42

torch.manual_seed(seed=seed_number)
randoz=torch.rand(3,3)


torch.manual_seed(seed=seed_number)
randoz2=torch.rand(3,3)

randoz==randoz2

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [1]:
#CUDA


!nvidia-smi

Fri Jul  8 13:02:50 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import torch

device='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
torch.cuda.device_count()

1

In [6]:
tensor=torch.tensor([1,4,6,3])
tensorgpu=tensor.to(device)

In [7]:
tensorgpu

tensor([1, 4, 6, 3], device='cuda:0')

In [8]:
tensorcpu=tensorgpu.cpu().numpy()

In [9]:
tensorcpu

array([1, 4, 6, 3])

In [18]:
#excercises:

xrand=torch.rand((7,7))
xrand

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [19]:
yrand=torch.rand((1,7))

In [20]:
result=torch.mm(xrand, yrand.T)
result

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [42]:
seed_number=0
torch.manual_seed(seed=seed_number)
arand=torch.rand(size=(7,7))
brand=torch.rand(size=(1,7))

result=torch.mm(arand,brand.T)

print(result,result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


In [44]:
seed_number=1234
torch.manual_seed(seed=seed_number)
qrand=torch.rand((2,3))

#torch.manual_seed(seed=seed_number)
wrand=torch.rand((2,3))

#result=torch.mm(qrand,wrand.T)

print(qrand)

print(wrand)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


In [45]:
result=torch.mm(qrand,wrand.T)

print(result.max(), result.min())

print(result.argmax(), result.argmin())

tensor(0.5617) tensor(0.3647)
tensor(3) tensor(0)


In [46]:
torch.manual_seed(seed=7)
rando=torch.rand(1,1,1,10)

#cropped=rando[:,:,:,]

cropped=rando.squeeze()

print(cropped,cropped.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
