<a href="https://colab.research.google.com/github/abhishekmani12/Pytorch_Stuff/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

**Multiplying Tensors:**

In [5]:
x=torch.Tensor([3,2])
y=torch.Tensor([21,80])

result=x*y
print(result)

tensor([ 63., 160.])


In [7]:
result.shape

torch.Size([2])

**Empty / Zero array:**

In [4]:
empty=torch.zeros([4,4])
print(empty)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

**Array of Random Values:**

In [10]:
z=torch.rand([4,4])
z

tensor([[0.1110, 0.6634, 0.8638, 0.2999],
        [0.9482, 0.0129, 0.4900, 0.9467],
        [0.1853, 0.3737, 0.2357, 0.8817],
        [0.6396, 0.8546, 0.3520, 0.9663]])

**Reshaping an Array:**

In [11]:
z.view([8,2])

tensor([[0.1110, 0.6634],
        [0.8638, 0.2999],
        [0.9482, 0.0129],
        [0.4900, 0.9467],
        [0.1853, 0.3737],
        [0.2357, 0.8817],
        [0.6396, 0.8546],
        [0.3520, 0.9663]])